# Generated by Django 3.2.8 on 2021-11-03 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211029_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='last_name',
        ),
    ]
