
@host_api = http://localhost:8000

### GET ALL SNIPPETS WITH ACCEPT HEADER

@accept_type = application/json
# @accept_type = text/html
GET {{host_api}}/snippets
Accept: {{accept_type}}

### GET ALL SNIPPETS WITH SUFFIX FORMAT

@suffix_format = json
# @suffix_format = api
GET {{host_api}}/snippets.{{suffix_format}}

### 

@snippet_id = 2
@user = user2
@pass = s3cr3t_p4ss
PUT  {{host_api}}/snippets/{{snippet_id}}/
Accept: {{accept_type}}
Content-Type: application/json
Authorization: Basic {{user}}:{{pass}}

{
    "title": "Python Hello World examples!",
    "code": "#include <stdio.h>\r\nprintf(\"Hello %s\"!, \"World\");",
    "linenos": false,
    "language": "c",
    "style": "material",
    "owner": "user2"
}

###

{
    "first_name": "Juan",
    "last_name": "Palote",
    "email": "jaunpalote@gmail.com"
}


###

{
    "question_id": 1,
    "option_id": 1
}