# Generated by Django 3.2.7 on 2021-10-06 23:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assesment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('desription', models.TextField(max_length=500)),
                ('thanks_message', models.TextField(default='<p>Thanks for complete the assesment!</p>', max_length=100)),
                ('language', models.CharField(blank=True, choices=[('python', 'python'), ('java', 'java'), ('c', 'c'), ('ruby', 'ruby'), ('javascript', 'javascript')], default='python', help_text='The assesment languaje', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Taker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True)),
                ('experience_years', models.IntegerField(blank=True, default=0)),
                ('current_position', models.CharField(blank=True, default='', max_length=200)),
                ('mobile_phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('profile', models.CharField(blank=True, default='', max_length=200)),
                ('genre', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('n', 'No binary')], default='', help_text='Taker genre', max_length=1)),
                ('nationality', models.CharField(blank=True, choices=[('AR', 'Argentina'), ('US', 'United States')], default='US', help_text='Taker nationality', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('question_type', models.CharField(choices=[('m', 'Multiple choice'), ('t', 'Text resolution')], default='m', help_text='Type of question', max_length=1)),
                ('assesment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assesments.assesment')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('option_type', models.CharField(choices=[('Selection', 'Selection'), ('Text', 'Text'), ('Code', 'Code')], default='Selection', max_length=30)),
                ('assesment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assesments.question')),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('duration', models.IntegerField(default=60)),
                ('score', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('active', models.BooleanField(default=False)),
                ('progress_status', models.JSONField()),
                ('assesment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assesments.assesment')),
                ('taker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='assesments.taker')),
            ],
        ),
    ]
