# Generated by Django 3.2.7 on 2021-10-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assesments', '0002_rename_assesment_option_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taker',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
