# Generated by Django 3.2.7 on 2021-10-07 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assesments', '0003_alter_taker_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assesment',
            old_name='desription',
            new_name='description',
        ),
    ]
