# Generated by Django 3.2.7 on 2021-10-07 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assesments', '0004_rename_desription_assesment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='assesment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='assesments.assesment'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='end_date',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='progress_status',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='start_date',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='taker',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='assesments.taker'),
        ),
    ]
