# Generated by Django 3.2.7 on 2021-10-07 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assesments', '0005_auto_20211007_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='instance',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
