# Generated by Django 3.2.7 on 2021-10-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assesments', '0006_auto_20211007_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='end_date',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='start_date',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
