# Generated by Django 3.2.8 on 2021-10-14 20:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assesments', '0007_assesment_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='instance',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
