# Generated by Django 3.2.8 on 2021-10-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assesments', '0009_instance_finalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='question_index',
            field=models.IntegerField(default=0),
        ),
    ]
