# Generated by Django 3.2.8 on 2021-10-31 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assesments', '0010_instance_question_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taker',
            options={},
        ),
        migrations.RemoveField(
            model_name='taker',
            name='email',
        ),
        migrations.RemoveField(
            model_name='taker',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='taker',
            name='last_name',
        ),
        migrations.AddField(
            model_name='taker',
            name='api_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taker',
            name='nationality',
            field=models.CharField(blank=True, choices=[('AR', 'Argentina'), ('US', 'United States')], default='', help_text='Taker nationality', max_length=2),
        ),
    ]
