# Generated by Django 3.2.8 on 2021-10-31 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assesments', '0011_auto_20211031_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taker',
            old_name='api_user',
            new_name='user',
        ),
    ]
