# Generated by Django 3.2.8 on 2021-11-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assesments', '0012_rename_api_user_taker_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='taker',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='taker',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
